apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    generation: 4
    labels:
      k8s-app: heapster
      kubernetes.io/cluster-service: "true"
      version: v1.1.0
    name: heapster-v1.1.0
    namespace: kube-system
    resourceVersion: "4234"
    selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/heapster-v1.1.0
    uid: dc12db53-5ad7-11e6-b082-120157131d3d
  spec:
    replicas: 1
    selector:
      matchLabels:
        k8s-app: heapster
        version: v1.1.0
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: heapster
          version: v1.1.0
      spec:
        containers:
        - command:
          - /heapster
          - --source=kubernetes.summary_api:''
          - --sink=influxdb:http://monitoring-influxdb:8086
          image: gcr.io/google_containers/heapster:v1.1.0
          imagePullPolicy: IfNotPresent
          name: heapster
          resources:
            limits:
              cpu: 88m
              memory: 204Mi
            requests:
              cpu: 88m
              memory: 204Mi
          terminationMessagePath: /dev/termination-log
        - command:
          - /eventer
          - --source=kubernetes:''
          - --sink=influxdb:http://monitoring-influxdb:8086
          image: gcr.io/google_containers/heapster:v1.1.0
          imagePullPolicy: IfNotPresent
          name: eventer
          resources:
            limits:
              cpu: 100m
              memory: 205800Ki
            requests:
              cpu: 100m
              memory: 205800Ki
          terminationMessagePath: /dev/termination-log
        - command:
          - /pod_nanny
          - --cpu=80m
          - --extra-cpu=0.5m
          - --memory=140Mi
          - --extra-memory=4Mi
          - --threshold=5
          - --deployment=heapster-v1.1.0
          - --container=heapster
          - --poll-period=300000
          - --estimator=exponential
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: gcr.io/google_containers/addon-resizer:1.3
          imagePullPolicy: IfNotPresent
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 92560Ki
            requests:
              cpu: 50m
              memory: 92560Ki
          terminationMessagePath: /dev/termination-log
        - command:
          - /pod_nanny
          - --cpu=100m
          - --extra-cpu=0m
          - --memory=190Mi
          - --extra-memory=500Ki
          - --threshold=5
          - --deployment=heapster-v1.1.0
          - --container=eventer
          - --poll-period=300000
          - --estimator=exponential
          env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: gcr.io/google_containers/addon-resizer:1.3
          imagePullPolicy: IfNotPresent
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 92560Ki
            requests:
              cpu: 50m
              memory: 92560Ki
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    observedGeneration: 4
    replicas: 1
    updatedReplicas: 1
kind: List
metadata: {}
